name: synchron_app
description: Application de synchronisation mobile via SSH
version: 1.0.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.3
  dartssh2: ^2.5.0
  path_provider: ^2.0.14
  shared_preferences: ^2.2.1
